# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-19 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_content_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_html',
            field=models.TextField(blank=True, verbose_name='正文HTML代码'),
        ),
    ]
